name: CI Pipeline

on:
  push:
    branches:
      - master
      - main
      - feature-*

jobs:
  build:
    runs-on: ubuntu-latest

    steps:

    - name: Checkout code
      uses: actions/checkout@v4

    - name: Setup Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.11'

    - name: Install backend dependencies
      run: |
        cd backend
        pip install fastapi uvicorn pymongo

    - name: Run backend server check
      run: |
        cd backend
        python -c "print('Backend OK')"

    - name: Setup Node
      uses: actions/setup-node@v4
      with:
        node-version: '18'

    - name: Install frontend dependencies
      run: |
        cd frontend
        npm install

    - name: Build frontend
      run: |
        cd frontend
        npm run build

    - name: Success message
      run: echo "CI Pipeline Passed"

    - name: Login to Docker Hub
      run: |
        echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin

    - name: Build Docker image
      run: |
        docker build -t ruchitamoger/task-manager-app:latest ./backend

    - name: Push Docker image
      run: |
        docker push ruchitamoger/task-manager-app:latest